import type { Metadata } from "next";
import MainHeader from "./components/mainHeader/mainHeader";
import "./reset.css";
import "./globals.css";

export const metadata: Metadata = {
	title: "Addresses",
	description: "Generated by create next app",
};

export default function RootLayout({
	children,
}: Readonly<{
	children: React.ReactNode;
}>) {
	return (
		<html lang="en">
			<body>
				<MainHeader />
				{children}
			</body>
		</html>
	);
}
